name: CI Rust

on:
  push:
    branches:
      - "master"
      - "release/[1-9]**"
    tags:
      - "v[1-9]**"
  pull_request:
    branches:
      - "master"
      - "release/[1-9]**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build.
        run: cargo build --verbose
      - name: Test.
        run: cargo test --verbose
      - name: Proper formatting!
        run: cargo fmt --verbose --all -- --check
      - name: No Dirtiness!
        run: git diff --exit-code
  release-artifacts:
    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
    needs:
      - build
    strategy:
      matrix:
        platform:
          - macos-13 # x86_64
          - macos-14 # arm64
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Build/Test Release Binary.
        run: |
          cargo build --release --verbose
          cargo test --release --verbose
          ./target/release/lgrep --version
      - name: Upload Release Binary.
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/heads/release/')
        with:
          name: lgrep-${{ matrix.platform == 'macos-13' && 'macOS-x86_64'
            || matrix.platform == 'macos-14' && 'macOS-arm64'
            || 'Linux-x86_64'}}
          path: target/release/lgrep
