name: CI

on:
  push:
    branches:
      - "master"
      - "release/[1-9][0-9]*.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "master"
      - "release/[1-9][0-9]*.[0-9]+.[0-9]+"

jobs:
  ci:
    uses: ./.github/workflows/build-and-verify.yml
