on:
  push:
    tags:
      - "v[1-9][0-9]*.[0-9]+.[0-9]+"

jobs:
  ci-sanity-check:
    uses: ./.github/workflows/build-and-verify.yml

  set-up-release:
    needs:
      - ci-sanity-check
    runs-on: ubuntu-latest
    steps:
      - name: Annotated!
        run: |
          git show ${{ github.ref_name }} \
          | egrep 'Tagger|commit' \
          | head -n 1 \
          | grep Tagger > /dev/null
      - name: Create Release.
        run: |
          gh release create ${{ github.ref_name }} \
          --verify-tag \
          --title "${{ github.ref_name }}" \
          --notes-from-tag \
          --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-binaries:
    needs:
      - set-up-release
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout.
        uses: actions/checkout@v4
      - name: Build.
        run: cargo build --release --verbose
      - name: Tests!
        run: cargo test --release --verbose
      - name: Version.
        run: ./target/release/lgrep --version
      - name: Upload.
        run: |
          gh release upload ${{ github.ref_name }} \
          "./target/release/lgrep#lgrep (${{ matrix.platform }})"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

